services:
  - type: web
    name: frontend
    env: node
    plan: free
    region: global
    buildCommand: "cd frontend_nextjs && npm install && npm run build"
    startCommand: "cd frontend_nextjs && npm run start"